#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include customize.yaml
default_config:
updater:
  reporting: false
discovery:
  ignore:
    - harmony
stream:
http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 10
logger:
  default: warn
  logs:
    homeassistant.components.unifiprotect: info

#################################################################
## Components
#################################################################

lutron_caseta_pro:
  bridges:
    - host: lutron.network.REDACTED
      mac: !secret lutron_caseta_pro_mac
      switch: [ 17, 22 ]

wemo:
  discovery: true
  static:
    - REDACTED.220
    - REDACTED.221
    - REDACTED.222
    - REDACTED.223
    - REDACTED.225
    - REDACTED.226

webostv:
  host: 'bedroom-tv.network.REDACTED'
  name: Bedroom TV

media_player:
  - platform: yamaha
    name: "Surround Sound Receiver"
    host: 'receiver.network.REDACTED'
    source_ignore:
      - "AUX"
      - "AV1"
      - "AV2"
      - "AV3"
      - "Bluetooth"
      - "Deezer"
      - "MusicCast Link"
      - "NET RADIO"
      - "Pandora"
      - "SERVER"
      - "Spotify"
      - "TIDAL"
      - "TUNER"
      - "USB"
    source_names:
      HDMI1: "Apple TV"
      HDMI2: "Xbox One X"
      HDMI3: "Nintendo Switch"
      HDMI4: "Wii U"
      AUDIO1: "TV Audio"
      AUDIO2: "Sonos Digital"
      AUDIO3: "Sonos"

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key

google:
  client_id: !secret google_client_id
  client_secret: !secret goole_client_secret
  track_new_calendar: true

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
    name: "REDACTED, MO"

alarm_control_panel:
  - platform: manual
    name: Alarm
    code_arm_required: false
    arming_time: 30
    delay_time: 30
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 30
      trigger_time: 60
      arming_time: 30
    armed_away:
      delay_time: 15
      trigger_time: 120
      arming_time: 30

route53:
  aws_access_key_id: !secret aws_access_key_id_route53
  aws_secret_access_key: !secret aws_secret_access_key_route53
  zone: !secret aws_zone_route53
  domain: !secret aws_domain_route53
  records:
    - home

octoprint:
  host: 3d-printer.network.REDACTED
  api_key: !secret octoprint_api
  name: 3D Printer
  bed: true
  number_of_tools: 1

camera:
  - platform: mjpeg
    name: 3D Printer
    still_image_url: http://3d-printer.network.REDACTED/webcam/?action=snapshot
    mjpeg_url: http://3d-printer.network.REDACTED/webcam/?action=stream

#influxdb:
#  host: 'influxdb.network.REDACTED'
#  database: !secret influxdb_database
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  include:
#    entities:
#      - climate.main_floor
#      - climate.office_fan
#      - sensor.living_room_temperature
#      - sensor.main_floor_temperature
#      - sensor.kitchen_temperature
#      - sensor.bedroom_temperature
#      - sensor.bathroom_temperature
#      - sensor.office_temperature
#      - sensor.USER2_office_temperature
#      - sensor.guest_bedroom_temperature
#      - sensor.basement_temperature
#      - sensor.laundry_room_temperature
#      - sensor.garage_temperature
#      - sensor.main_floor_humidity
#      - sensor.office_fan_humidity
#      - sensor.REDACTED_humidity
#      - sensor.REDACTED_temperature
#      - sensor.nas_status
#      - sensor.nas_smart_status_drive_0_1
#      - sensor.nas_smart_status_drive_0_2
#      - sensor.nas_smart_status_drive_0_3
#      - sensor.nas_smart_status_drive_0_4
#      - sensor.nas_cpu_usage
#      - sensor.nas_memory_usage
#      - sensor.nas_volume_used_storage
#      - sensor.nas_system_temperature
#      - sensor.uptime
#      - sensor.ups_status
#      - sensor.ups_battery_runtime_mins
#      - sensor.ups_input_voltage
#      - sensor.ups_battery_charge

#################################################################
## Notifications
#################################################################

notify:
  - platform: group
    name: REDACTED_devices
    services:
      - service: mobile_app_REDACTEDs_iphone
      - service: mobile_app_REDACTED_s_ipad
      - service: mobile_app_REDACTEDs_imac

  - platform: group
    name: USER2_devices
    services:
      - service: mobile_app_USER2_s_iphone
      - service: mobile_app_USER2_s_ipad

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
group: !include groups.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
light: !include light_group.yaml
homekit: !include homekit.yaml
ios: !include ios.yaml
switch: !include switch.yaml
emulated_hue: !include emulated_hue.yaml
cover: !include cover_group.yaml
cloud: !include cloud.yaml