#################################################################
## 3D Printer Automations
#################################################################

        ##########################################################
        ## 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Print Finished
  id: '3d_printer_print_finished'

  trigger:
    - platform: state
      entity_id: binary_sensor.3d_printer_printing
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: 3D Print Complete
        data:
          apns_headers:
           'apns-collapse-id': '3d-print'
          push:
            category: camera
          entity_id: camera.3d_printer